language:  generic

notifications:
    slack:
        rooms:
            - zeeql:odi4PEJUdmDPkBfjhHIaSdrS

matrix:
    include:
        - os:   osx
          osx_image: xcode9
    include:
        - os:   osx
          osx_image: xcode9.2
    include:
        - os:   osx
          osx_image: xcode9.3
    include:
        - os:   osx
          osx_image: xcode11

script:
    - set -o pipefail
    - xcodebuild -scheme UXKit-AppKit -configuration Debug   -target UXKit-AppKit | xcpretty
    - xcodebuild -scheme UXKit-UIKit  -configuration Release -target UXKit-UIKit -destination generic/platform=iOS | xcpretty

